baseurl = "https://www.katzien.de"
title = "Jan Katins"

theme = "hugo-coder"

languagecode = "en"
defaultcontentlanguage = "en"
# to get the redirects form the old structure
defaultContentLanguageInSubdir = true

paginate = 20
canonifyurls = true

pygmentsstyle = "friendly"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[params]
# If you change something here, also change stuff in de!
author = "Jan Katins"
description = "Python Software Enginnee / Data Engineer | Python enthusiast ([knitpy](https://github.com/jankatins/knitpy), pandas, statsmodels, matplotlib, ggplot/plotnine, [pypandoc](https://github.com/bebraw/pypandoc)) | Jupyter R Kernel | Ex PhD student @ TU Freiberg (bibliometrics, academic research productivity, social networks, social capital). Formerly Jan Schulz"
keywords = "blog,developer,personal,Katzien,Anderer Dienst im Ausland"
info = "Python Developer & Data Engineer"
avatarurl = "/images/jan.jpg"
footercontent = "This work is licensed under a <a href='https://creativecommons.org/licenses/by/4.0/'>Creative Commons Attribution 4.0 International License</a> or under a <a href='https://opensource.org/licenses/MIT'>MIT License</a> (e.g. any code)"
fediverseCreator = "@jankatins@fosstodon.org "
#needs to be second januar of 2006!
dateformat = "2006-01-02"
since = "2002"
hideCredits = false
hideCopyright = false

# Git Commit in Footer, uncomment the line below to enable it.
#commit = "https://github.com/luizdepra/hugo-coder/tree/"

rtl = false

# Use inverted colors
inverted = false

# Custom CSS
customCSS = ["css/local.css", "css/fixes.css"]

[params.giscus] # https://giscus.app
repo = "jankatins/katzien.de"
repoID = "MDEwOlJlcG9zaXRvcnkyMDE4MjQ3MjQ="
category = "Announcements"
categoryID = "DIC_kwDODAeZ1M4CfuNL"
mapping = "pathname"
term = ""
strict = "1"
reactionsEnabled = "1"
emitMetadata = "1"
inputPosition = "top"
theme = "preferred_color_scheme"
lang = "en"
loading = "lazy"

[taxonomies]
tags = "tags"

[[params.social]]
name = "Github"
icon = "fa fa-github"
weight = 1
url = "https://github.com/jankatins/"
rel = "me"
[[params.social]]
name = "Twitter"
icon = "fa fa-twitter"
weight = 3
url = "https://twitter.com/jankatins/"
rel = "me"
[[params.social]]
name = "Mastodon"
icon = "fa fa-mastodon"
weight = 3
url = "https://fosstodon.org/@jankatins"
rel = "me"
[[params.social]]
name = "LinkedIn"
icon = "fa fa-linkedin"
weight = 4
url = "https://www.linkedin.com/in/jankatins/"
rel = "me"
[[params.social]]
name = "Xing"
icon = "fa fa-xing"
weight = 5
url = "https://www.xing.com/profile/Jan_Katins/cv"
rel = "me"


[languages]
[languages.en]
languagename = "English"

[[languages.en.menu.main]]
name = "About"
weight = 1
url = "/en/about/"

[[languages.en.menu.main]]
name = "Blog"
weight = 2
url = "/en/posts/"

[[languages.en.menu.main]]
name = "Contact me"
weight = 5
url = "/en/contact/"


[languages.de]
languagename = "Deutsch"
title = "Jan Katins"

[languages.de.params]
author = "Jan Katins"
info = "Python Developer & Data Engineer"
description = "Python Developer, Data Engineer, Anderer Dienst im Ausland, früher mal aus Katzien"
keywords = "Katzien,ADiA,Anderer Dienst im Ausland"
footercontent = ""

[languages.de.menu]

[[languages.de.menu.main]]
name = "Über"
weight = 1
url = "/de/about/"

[[languages.de.menu.main]]
name = "Katzien"
weight = 2
url = "/de/katzien/"

[[languages.de.menu.main]]
name = "Anderer Dienst im Ausland"
weight = 3
url = "/de/adia/"

[[languages.de.menu.main]]
name = "Kontakt"
weight = 5
url = "/de/contact/"
